controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Users;
use app\models\House;
use app\models\Clients;
use app\models\ClientsHouses;
use app\models\Nastroyka;

class SiteController extends Controller
{
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['dashboard', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->isGuest) { 
            return $this->redirect('site/boards-project');
        }else
        {
            return $this->redirect(['site/login']);
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Рабочий стол
     * через этот екшн заходим на Рабочий стол
     * @return Response|string
     */     
    public function actionDashboard()
    {
      if (Yii::$app->user->isGuest) { 
        return $this->redirect(['site/login']);
      }
        return $this->render('dashboard', [
            'all_tasks' => $result1,
            'result' => $result,
            'comment' => $comment,
            'total_hour' => $total_hour,
            'tasks' => $all_tasks,
        ]);
    }
    public function actionHouse()
    {
        return $this->redirect(['house/apartment', 'type' => 4]);
    }
    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
         Yii::$app->user->logout();

        $this->redirect(['login']);
    }

    public function actionAvtorizatsiya()
    {
      if(isset(Yii::$app->user->identity->id))
      {
        return $this->render('error');
      }        
      else
      {
          Yii::$app->user->logout();
          $this->redirect(['login']);
      }
    }
    
    public function actionEarned($year = null, $month = null)
    { 
      if($year == null)  $year = date('Y');  
      if($month == null)  $month = date('m');
      $apartment_long = House::find()->where(['house_type' => 1])->count();
      $room_long = House::find()->where(['house_type' => 3])->count();
      $home_long = House::find()->where(['house_type' => 5])->count();

      $apartment_short = House::find()->where(['house_type' => 2])->count();
      $room_short= House::find()->where(['house_type' => 4])->count();
      $home_short = House::find()->where(['house_type' => 6])->count();

      $clients = Clients::find()->count();

      $min_litsenzed = ClientsHouses::find()->min('date_add_commission');
      $max_litsenzed = ClientsHouses::find()->max('date_add_commission');

      return $this->render('earned', [
          'model' => new ClientsHouses(),
          'apartment_long' => $apartment_long,
          'room_long' => $room_long,
          'home_long' => $home_long,
          'apartment_short' => $apartment_short,
          'room_short' => $room_short,
          'home_short' => $home_short,
          'clients' => $clients,
          'year' => $year,
          'month' => $month,
          'min_litsenzed' => \Yii::$app->formatter->asDate($min_litsenzed. Yii::$app->getTimeZone(), 'php:Y'),
          'max_litsenzed' => \Yii::$app->formatter->asDate($max_litsenzed. Yii::$app->getTimeZone(), 'php:Y'),
      ]);
    }

    // через этот екшн можно войти на инструкцию
    public function actionInstruksion()
    {
        if (Yii::$app->user->isGuest)   return $this->redirect(['site/login']);
        return $this->render('instruksion', []);        
    }

    public function actionMap()
    {
      return $this->render('map', []);
    }

    public function actionTuning()
    {
        $request = Yii::$app->request;
        $model = Nastroyka::find()->where(['user_id' => Yii::$app->user->id])->one();
        if($model == null){
            $model = new Nastroyka();
            $model->user_id = Yii::$app->user->id;
            $model->coordinate_x = '55.753187580818675';
            $model->coordinate_y = '37.62333811759736';
            $model->city = "Москва";
            $model->location_metro = "метро Площадь Революции";
            $model->address = "улица Ильинка";
            $model->dom = " 7";
        }
/*echo "<pre>";
print_r($request->post());
echo "</pre>";
die;*/
        if ($model->load($request->post()) && $model->save()) {
            return $this->redirect(['site/dashboard']);
        } else {
            return $this->render('_form_nastroyka', [
                'model' => $model,
            ]);
        }
    }
}

views/yii2-app/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;

?>

<section class="content" id="content">

    <?php if (isset($this->blocks['content-header'])) { ?>
        <h1 class="page-header">Basic Tables</h1>
    <?php } else { ?>
    <?php } ?>

    <!--         <?=
    Breadcrumbs::widget(
        [
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]
    ) ?> -->

    <?= $content ?>
</section>

views/yii2-app/layouts/header-menu.php
<?php

use yii\helpers\Url;

?>

<div id="top-menu" class="top-menu">
    <?php if(Yii::$app->user->isGuest == false): ?>
        <?php
        echo \app\admintheme\widgets\TopMenu::widget(
            [
                'options' => ['class' => 'nav'],
                'items' => [
                    // ['label' => 'Рабочий стол', 'icon' => 'fa fa-desktop', 'url' => ['site/dashboard'], ],
                    ['label' => 'Квартиры', 'icon' => 'fa  fa-home', 'url' => 'javascript:;',
                        'options' => [ 'class' => 'has-sub', ],
                        'items' => [
                            ['label' => 'На длительный срок', 'url' => ['/house/apartment', 'type' => 4],],
                            ['label' => 'Посуточно ', 'url' => ['/house/apartment', 'type' => 7],],
                        ],
                    ],
                    ['label' => 'Комнаты', 'icon' => 'fa  fa-home', 'url' => 'javascript:;',
                        'options' => [ 'class' => 'has-sub', ],
                        'items' => [
                            ['label' => 'На длительный срок', 'url' => ['/house/apartment', 'type' => 5],],
                            ['label' => 'Посуточно ', 'url' => ['/house/apartment', 'type' => 8],],
                        ],
                    ],
                    ['label' => 'Дома', 'icon' => 'fa  fa-home', 'url' => 'javascript:;',
                        'options' => [ 'class' => 'has-sub', ],
                        'items' => [
                            ['label' => 'На длительный срок', 'url' => ['/house/apartment', 'type' => 6],],
                            ['label' => 'Посуточно ', 'url' => ['/house/apartment', 'type' => 9],],
                        ],
                    ],
                    //['label' => 'Квартиры', 'url' => ['/house/apartment', 'type' => 1], ],
                    //['label' => 'Комнаты', 'url' => ['/house/apartment', 'type' => 2], ],
                    //['label' => 'Дома', 'url' => ['/house/apartment', 'type' => 3], ],
                    ['label' => 'Клиенты', 'icon' => 'fa  fa-user', 'url' => ['/clients'], ],
                    ['label' => 'Заработано',  'icon' => 'fa  fa-cubes','url' => ['/site/earned'], ],
                    ['label' => 'Пользователи', 'icon' => 'fa fa-users', 'url' => ['/users/index'], ],
                ],
            ]
        );
        ?>
    <?php endif; ?>
</div>

views/yii2-app/layouts/header.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Modal;
use johnitvn\ajaxcrud\CrudAsset; 

CrudAsset::register($this);
?>
<div id="ajaxCrudDatatable">
<div id="header" class="header navbar navbar-default navbar-fixed-top">
    <!-- begin container-fluid -->
    <div class="container-fluid">
        <!-- begin mobile sidebar expand / collapse button -->
        <div class="navbar-header">
            <a href="<?=Yii::$app->homeUrl?>" class="navbar-brand"><span class="navbar-logo"></span> Makler</a>
            <button type="button" class="navbar-toggle" data-click="top-menu-toggled">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- end mobile sidebar expand / collapse button -->

        <!-- begin header navigation right -->
        <ul class="nav navbar-nav navbar-right">
            <li>
                <?php // Html::a('Настройки', ['/site/tuning'], [ ])?>
                <?= Html::a('Настройки', ['/#'], [ ])?>
            </li>
            <li>
                <?php // Html::a('Инструкция', ['/site/instruksion'], [ ])?>
                <?= Html::a('Инструкция', ['/#'], [ ])?>
            </li>
            <li><?= Html::a('Профиль', 
                    ['/users/view', 'id' => Yii::$app->user->identity->id], 
                    [
                        /*'role'=>'modal-remote',*/ 'data-pjax' => 0, 'title'=>'Изменить профиля',
                        'data-confirm'=>false, 'data-method'=>false,
                        'data-request-method'=>'post',
                    ]
                )?>
            </li>
            <li class="dropdown navbar-user">
                <?= Html::a('Выйти', ['/site/logout'], ['data-method' => 'post'] ) ?>
            </li>
        </ul>
        <!-- end header navigation right -->
    </div>
    <!-- end container-fluid -->
</div>
</div>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "size" => "modal-lg",
    "options" => [
        "tabindex" => -1,
    ],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/yii2-app/layouts/main-login.php
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <title>Авторизация</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />

    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="/theme/assets/plugins/jquery-ui/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
    <link href="/theme/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/theme/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/theme/assets/css/animate.min.css" rel="stylesheet" />
    <link href="/theme/assets/css/style.min.css" rel="stylesheet" />
    <link href="/theme/assets/css/style-responsive.min.css" rel="stylesheet" />
    <!-- ================== END BASE CSS STYLE ================== -->

    <!-- ================== BEGIN BASE JS ================== -->
    <script src="theme/assets/plugins/pace/pace.min.js"></script>
    <!-- ================== END BASE JS ================== -->
</head>
<body class="pace-top">
<!-- begin #page-loader -->
<div id="page-loader" class="fade in"><span class="spinner"></span></div>
<!-- end #page-loader -->

<!-- begin #page-container -->
<div id="page-container" class="fade">
    <!-- begin login -->
    <?=$content?>
    <!-- end login -->

</div>
<!-- end page container -->

<!-- ================== BEGIN BASE JS ================== -->
<script src="/theme/assets/plugins/jquery/jquery-1.9.1.min.js"></script>
<script src="/theme/assets/plugins/jquery/jquery-migrate-1.1.0.min.js"></script>
<script src="/theme/assets/plugins/jquery-ui/ui/minified/jquery-ui.min.js"></script>
<script src="/theme/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<!--[if lt IE 9]>
<script src="/theme/assets/plugins/crossbrowserjs/html5shiv.js"></script>
<script src="/theme/assets/plugins/crossbrowserjs/respond.min.js"></script>
<script src="/theme/assets/plugins/crossbrowserjs/excanvas.min.js"></script>
<![endif]-->
<script src="/theme/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>
<script src="/theme/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
<!-- ================== END BASE JS ================== -->

<!-- ================== BEGIN PAGE LEVEL JS ================== -->
<script src="/theme/assets/js/apps.min.js"></script>
<!-- ================== END PAGE LEVEL JS ================== -->

<script>
    $(document).ready(function() {
        App.init();
    });
</script>
</body>
</html>

views/yii2-app/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

$theme = "default";


if (Yii::$app->controller->action->id === 'login') {
    /**
     * Do not use this code in your template. Remove it.
     * Instead, use the code  $this->layout = '//main-login'; in your controller.
     */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
}
else
if (Yii::$app->controller->action->id === 'sign') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    app\assets\ColorAdminAsset::register($this);

    // dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <!-- ================== BEGIN BASE CSS STYLE ================== -->
        <?=$this->head()?>
        <link href="/css/theme/<?=$theme?>.css" rel="stylesheet">
        <!-- ================== END BASE CSS STYLE ================== -->
        <script src="/theme/assets/plugins/jquery/jquery-1.9.1.min.js"></script>
        <script src="/assets/pace/pace.min.js"></script>
    </head>
    <body>

    <?php $this->beginBody() ?>

    <div id="page-container" class="page-container fade page-without-sidebar page-header-fixed page-with-top-menu in">
        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'header-menu.php',
            ['directoryAsset' => $directoryAsset]
        )?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>


    </div>





    <?php $this->endBody() ?>

    <script>
        $(document).ready(function() {
            App.init();
        });
    </script>




    <style>
        [title='Выберите формат файла для экспорта']{
            padding: 3px !important;
            padding-bottom: 2px !important;
        }
    </style>
    <script>


        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-53034621-1', 'auto');
        ga('send', 'pageview');

    </script>
    <script>

    </script>

    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>