controllers/HouseController.php
<?php

namespace app\controllers;

use Yii;
use app\models\House;
use app\models\HouseSearch;
use yii\web\Controller; 
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\UploadForm;
use yii\web\UploadedFile;
use app\models\Directory;
use app\models\HouseFile;
use app\models\OwnerContacts;
use app\models\Clients; 
use app\models\ClientsHouses;
use app\models\Columns;
use app\models\HouseDocuments;
use yii\data\ActiveDataProvider;

class HouseController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                   [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all House models.
     * @return mixed
     */
    public function actionApartment($type)
    {    
        $searchModel = new HouseSearch();
        $post = Yii::$app->request->post();
        if(Yii::$app->request->queryParams['_pjax'] == null){
            $session = Yii::$app->session;
            $session['search_id'] = isset($post['HouseSearch']['search_id']) ? $post['HouseSearch']['search_id'] : '';
            $session['search_city'] = isset($post['HouseSearch']['search_city']) ? $post['HouseSearch']['search_city'] : '';
            $session['search_metro'] = isset($post['HouseSearch']['search_metro']) ? $post['HouseSearch']['search_metro'] : '';
            $session['search_address'] = isset($post['HouseSearch']['search_address']) ? $post['HouseSearch']['search_address'] : '';
            $session['search_owner_name'] = isset($post['HouseSearch']['search_owner_name']) ? $post['HouseSearch']['search_owner_name'] : '';
            $session['search_owner_surname'] = isset($post['HouseSearch']['search_owner_surname']) ? $post['HouseSearch']['search_owner_surname'] : '';
            $session['search_telephone'] = isset($post['HouseSearch']['search_telephone']) ? $post['HouseSearch']['search_telephone'] : '';
            $session['search_home_number'] = isset($post['HouseSearch']['search_home_number']) ? $post['HouseSearch']['search_home_number'] : '';
        }

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $type, $post);

        $apartment_long = House::find()->where(['house_type' => 1])->count();
        $room_long = House::find()->where(['house_type' => 3])->count();
        $home_long = House::find()->where(['house_type' => 5])->count();

        $apartment_short = House::find()->where(['house_type' => 2])->count();
        $room_short= House::find()->where(['house_type' => 4])->count();
        $home_short = House::find()->where(['house_type' => 6])->count();

        $clients = Clients::find()->count();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'post' => $post,
            'dataProvider' => $dataProvider,
            'apartment_long' => $apartment_long,
            'room_long' => $room_long,
            'home_long' => $home_long,
            'apartment_short' => $apartment_short,
            'room_short' => $room_short,
            'home_short' => $home_short,
            'type' => $type,
            'clients' => $clients,
        ]);
    }


    /**
     * Displays a single House model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $apartment_long = House::find()->where(['house_type' => 1])->count();
        $room_long = House::find()->where(['house_type' => 3])->count();
        $home_long = House::find()->where(['house_type' => 5])->count();

        $apartment_short = House::find()->where(['house_type' => 2])->count();
        $room_short= House::find()->where(['house_type' => 4])->count();
        $home_short = House::find()->where(['house_type' => 6])->count();

        $clients = Clients::find()->count();
        return $this->render('view', [
            'model' => $this->findModel($id),
            'apartment_long' => $apartment_long,
            'room_long' => $room_long,
            'home_long' => $home_long,
            'apartment_short' => $apartment_short,
            'room_short' => $room_short,
            'home_short' => $home_short,
            'clients' => $clients,
        ]);       
    }
    public function actionFloors($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request;
        $model = $this->findModel($id);        
        $model->scenario = House::SCENARIO_PARAMETER;
            
        if ($model->load($request->post()) && $model->save()) {
            return [
                'forceReload'=>'#crud-datatable-pjax',
                'forceClose' => true,
            ];
        } else {
            return [
                'title'=> "Этажность",
                'size' => 'normal',
                'content'=>$this->renderAjax('_floors', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default btn-sm pull-left','data-dismiss'=>"modal"]).
                    Html::button('Сохранить',['class'=>'btn btn-primary btn-sm','type'=>"submit"])
            ];
        }
    }
    public function actionDocumentsView($id)
    {
        $request = Yii::$app->request;
        $query = HouseDocuments::find()->where(['house_id' => $id]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        //$model = HouseDocuments::find()->where(['house_id' => $id])->all();
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Документы",
                    'size' => 'normal',
                    'content'=>$this->renderAjax('documents_view', [
                        'dataProvider' => $dataProvider,
                    ]),
                ];    
        }else{
            return $this->render('documents_view', [
                'dataProvider' => $dataProvider,
            ]);
        }
    }
    public function actionVideo($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request;
        $model = $this->findModel($id);        
        $model->scenario = House::SCENARIO_DESCRIPTION;
            
        if ($model->load($request->post()) && $model->save()) {
            return [
                'forceReload'=>'#crud-datatable-pjax',
                'forceClose' => true,
            ];
        } else {
            return [
                'title'=> "Видео",
                'size' => 'small',
                'content'=>$this->renderAjax('_video', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default btn-sm pull-left','data-dismiss'=>"modal"]).
                    Html::button('Сохранить',['class'=>'btn btn-primary btn-sm','type'=>"submit"])
            ];
        }
    }
    public function actionMetro($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request;
        $model = $this->findModel($id);        
        $model->scenario = House::SCENARIO_PARAMETER;
            
        if ($model->load($request->post()) && $model->save()) {
            return [
                'forceReload'=>'#crud-datatable-pjax',
                'forceClose' => true,
            ];
        } else {
            return [
                'title'=> "Метро рядом",
                'size' => 'small',
                'content'=>$this->renderAjax('_metro', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default btn-sm pull-left','data-dismiss'=>"modal"]).
                    Html::button('Сохранить',['class'=>'btn btn-primary btn-sm','type'=>"submit"])
            ];
        }
    }
    public function actionFio($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request;
        $model = $this->findModel($id);        
        $model->scenario = House::SCENARIO_OWNER;
            
        if ($model->load($request->post()) && $model->save()) {
            return [
                'forceReload'=>'#crud-datatable-pjax',
                'forceClose' => true,
            ];
        } else {
            return [
                'title'=> "Описание",
                'size' => 'normal',
                'content'=>$this->renderAjax('_fio', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default btn-sm pull-left','data-dismiss'=>"modal"]).
                    Html::button('Сохранить',['class'=>'btn btn-primary btn-sm','type'=>"submit"])
            ];
        }
    }
    public function actionDescription($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request;
        $model = $this->findModel($id);        
        $model->scenario = House::SCENARIO_DESCRIPTION;
            
        if ($model->load($request->post()) && $model->save()) {
            return [
                'forceReload'=>'#crud-datatable-pjax',
                'forceClose' => true,
            ];
        } else {
            return [
                'title'=> "Описание",
                'size' => 'normal',
                'content'=>$this->renderAjax('_description', [
                    'model' => $model,
                ]),

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Users;
use app\models\House;
use app\models\Clients;
use app\models\ClientsHouses;
use app\models\Nastroyka;

class SiteController extends Controller
{
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['dashboard', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->isGuest) { 
            return $this->redirect('site/boards-project');
        }else
        {
            return $this->redirect(['site/login']);
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Рабочий стол
     * через этот екшн заходим на Рабочий стол
     * @return Response|string
     */     
    public function actionDashboard()
    {
      if (Yii::$app->user->isGuest) { 
        return $this->redirect(['site/login']);
      }
        return $this->render('dashboard', [
            'all_tasks' => $result1,
            'result' => $result,
            'comment' => $comment,
            'total_hour' => $total_hour,
            'tasks' => $all_tasks,
        ]);
    }
    public function actionHouse()
    {
        return $this->redirect(['house/apartment', 'type' => 4]);
    }
    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
         Yii::$app->user->logout();

        $this->redirect(['login']);
    }

    public function actionAvtorizatsiya()
    {
      if(isset(Yii::$app->user->identity->id))
      {
        return $this->render('error');
      }        
      else
      {
          Yii::$app->user->logout();
          $this->redirect(['login']);
      }
    }
    
    public function actionEarned($year = null, $month = null)
    { 
      if($year == null)  $year = date('Y');  
      if($month == null)  $month = date('m');
      $apartment_long = House::find()->where(['house_type' => 1])->count();
      $room_long = House::find()->where(['house_type' => 3])->count();
      $home_long = House::find()->where(['house_type' => 5])->count();

      $apartment_short = House::find()->where(['house_type' => 2])->count();
      $room_short= House::find()->where(['house_type' => 4])->count();
      $home_short = House::find()->where(['house_type' => 6])->count();

      $clients = Clients::find()->count();

      $min_litsenzed = ClientsHouses::find()->min('date_add_commission');
      $max_litsenzed = ClientsHouses::find()->max('date_add_commission');

      return $this->render('earned', [
          'model' => new ClientsHouses(),
          'apartment_long' => $apartment_long,
          'room_long' => $room_long,
          'home_long' => $home_long,
          'apartment_short' => $apartment_short,
          'room_short' => $room_short,
          'home_short' => $home_short,
          'clients' => $clients,
          'year' => $year,
          'month' => $month,
          'min_litsenzed' => \Yii::$app->formatter->asDate($min_litsenzed. Yii::$app->getTimeZone(), 'php:Y'),
          'max_litsenzed' => \Yii::$app->formatter->asDate($max_litsenzed. Yii::$app->getTimeZone(), 'php:Y'),
      ]);
    }

    // через этот екшн можно войти на инструкцию
    public function actionInstruksion()
    {
        if (Yii::$app->user->isGuest)   return $this->redirect(['site/login']);
        return $this->render('instruksion', []);        
    }

    public function actionMap()
    {
      return $this->render('map', []);
    }

    public function actionTuning()
    {
        $request = Yii::$app->request;
        $model = Nastroyka::find()->where(['user_id' => Yii::$app->user->id])->one();
        if($model == null){
            $model = new Nastroyka();
            $model->user_id = Yii::$app->user->id;
            $model->coordinate_x = '55.753187580818675';
            $model->coordinate_y = '37.62333811759736';
            $model->city = "Москва";
            $model->location_metro = "метро Площадь Революции";
            $model->address = "улица Ильинка";
            $model->dom = " 7";
        }
/*echo "<pre>";
print_r($request->post());
echo "</pre>";
die;*/
        if ($model->load($request->post()) && $model->save()) {
            return $this->redirect(['site/dashboard']);
        } else {
            return $this->render('_form_nastroyka', [
                'model' => $model,
            ]);
        }
    }
}

views/clients/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Clients */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="clients-form">

    <?php $form = ActiveForm::begin(); ?>
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'fio')->textInput(['maxlength' => true]) ?>                
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'type')->dropDownList($model->getType(), []) ?>
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'category')->dropDownList($model->getCategory(), []) ?>
            </div>            
        </div>

        <div class="row">
            <div class="col-md-3">
                <?= $form->field($model, 'room_count')->dropDownList($model->getRoomsCountList(), []) ?>
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'budjet')->textInput(['type' => 'number']) ?>
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'mebel')->dropDownList($model->getMebel(), []) ?>
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'floor')->dropDownList($model->getFloorList(), []) ?>
            </div>            
        </div>

        <div class="row">
            <div class="col-md-4">
                <?= $form->field($model, 'last_call')->widget(
                    DatePicker::className(), [
                        'inline' => false,
                        'language' => 'ru',
                        'clientOptions' => [
                            'autoclose' => true,
                            'format' => 'dd.mm.yyyy',
                            'startView'=>'year',
                        ]
                    ])
                ?>
                <?= $form->field($model, 'telephone')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-8">
                <?= $form->field($model, 'comment')->textArea(['rows' => 5]) ?>
            </div>
            <!-- <div class="col-md-4">
               </div>         -->   
        </div>

        <div class="row">
            <br>
            <div class="col-md-4">
                <?= $form->field($model, 'why_call')->widget(
                    DatePicker::className(), [
                        'inline' => false,
                        'language' => 'ru',
                        'clientOptions' => [
                            'autoclose' => true,
                            'format' => 'dd.mm.yyyy',
                            'startView'=>'year',
                        ]
                    ])
                ?>
            </div>
            <div class="col-md-8">
                <?= $form->field($model, 'why_comment')->textArea(['rows' => 1]) ?>
            </div>
                      
        </div>

        <div style="display: none;">
            <?= $form->field($model, 'status')->textInput(['value' => '1']) ?>
        </div>

    	<?php if (!Yii::$app->request->isAjax){ ?>
    	  	<div class="form-group">
    	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    	    </div>
    	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/clients/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Clients */

?>
<div class="clients-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/clients/create_new.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Clients */

?>
<div class="clients-createnew">
    <?= $this->render('_form_new', [
        'model' => $model,
    ]) ?>
</div>

views/clients/house_columns.php
<?php
use yii\helpers\Url;
use app\models\OwnerContacts;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

return [
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'id',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'address',
        'label' => 'Адрес/Статус',
        'content' => function ($data) {
            if($data->status == 1)return '<a data-pjax=0 class="btn btn-default btn-sm" href="'.Url::toRoute(['house/view', 'id' => $data->id]).'">'.$data->address. ', ' . $data->dom .'</a>';
            if($data->status == 2)return '<a data-pjax=0 class="btn btn-success btn-sm" href="'.Url::toRoute(['house/view', 'id' => $data->id]).'">'.$data->address. ', ' . $data->dom .'</a>';
            if($data->status == 3)return '<a data-pjax=0 class="btn btn-danger btn-sm" href="'.Url::toRoute(['house/view', 'id' => $data->id]).'">'.$data->address. ', ' . $data->dom .'</a>';
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'house_type',
        'content' => function ($data) {
            if($data->house_type == 1 | $data->house_type == 2) return 'Кв';
            if($data->house_type == 3 | $data->house_type == 4) return 'Ком';
            if($data->house_type == 5 | $data->house_type == 6) return 'Дом';
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'house_type',
        'label' => 'Категория',
        'content' => function ($data) {
            if($data->house_type == 1 || $data->house_type == 3 || $data->house_type == 5) return 'Длит';
            if($data->house_type == 2 || $data->house_type == 4 || $data->house_type == 6) return 'Посут';
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'rooms_count',
        'label' => 'Кол-во Комнат',
        'content' => function ($data) {
            if($data->rooms_count == 0) return "Студия";
            else return $data->rooms_count;            
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'cost',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'floor',
        'content' => function ($data) {
            if($data->house_type == 5 || $data->house_type == 6){
                if($data->home_floor == 6) return '5+';
                else return $data->home_floor;
            }
            else return $data->house_floor. '/'. $data->floor;            
        },
    ],
    /*[
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'public_avito',
        'label' => 'Сайт',
        'content' => function ($data) {
            if($data->public_avito == 1) return 'Нет';
            else return 'Да';
        },
    ],*/
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'telephone',
        /*'content' => function ($data) {
            $contacts = OwnerContacts::find()->where(['house_id'=> $data->id])->one();
            return $contacts->telephone;
        },*/
    ],
    /*[
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],*/
];   

views/clients/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

$this->title = "Клиенты";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>

<div class="panel panel-inverse" data-sortable-id="ui-widget-2">
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-success btn-xs">Скрыт / Отображать</button>
            <button type="button" class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><?= Html::a('Отображать всех', ['/clients/index','type'=>0,], [])?></li>
                <li><?= Html::a('Скрыть тех кто снял', ['/clients/index','type'=>1,], [])?></li>
                <li><?= Html::a('Отображать тех кто снял', ['/clients/index','type'=>2,], [])?></li>
            </ul>
        </div>
        <h4 class="panel-title">Клиенты</h4>
    </div>

    <div class="panel-body">

        <div class="col-xs-12">
            <div class="row">
                <div class="col-sm-6 col-lg-4">
                    <h5>На длительный срок <span><?=($apartment_long + $room_long + $home_long)?></span></h5>
                    <div class="form-group">
                        <?= Html::a('<span class="btn btn-default btn-sm">Квартиры <span>'.$apartment_long.'</span></span>', ['/house/apartment','type' => 1], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 1], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm">Комнаты <span>'.$room_long.'</span></span>', ['/house/apartment','type' => 2], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 3], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm">Дома <span>'.$home_long.'</span></span>', ['/house/apartment','type' => 3], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 5], ['data-pjax'=>0,])?> 
                    </div>
                </div>
                <div class="col-sm-6 col-lg-4">
                    <h5>Посуточно <span><?=($apartment_short + $room_short + $home_short)?></span></h5>
                    <div class="form-group">
                        <?= Html::a('<span class="btn btn-default btn-sm">Квартиры <span>'.$apartment_short.'</span></span>', ['/house/apartment','type' => 1], ['data-pjax'=>0,])?>
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 2], ['data-pjax'=>0,])?>
                        <?= Html::a('<span class="btn btn-default btn-sm">Комнаты <span>'.$room_short.'</span></span>', ['/house/apartment','type' => 2], ['data-pjax'=>0,])?>
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 4], ['data-pjax'=>0,])?>
                        <?= Html::a('<span class="btn btn-default btn-sm">Дома <span>'.$home_short.'</span></span>', ['/house/apartment','type' => 3], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 6], ['data-pjax'=>0,])?>
                    </div>
                </div>
                <div class="col-sm-4 col-md-3">
                    <h5>Доп. нав</h5>
                    <div class="form-group">
                        <?= Html::a('<span class="btn btn-info btn-sm">Клиенты <span>'.$clients.'</span></span>', ['/clients'], ['data-pjax'=>0,])?>
                        <?= Html::a('<span class="btn btn-info btn-sm"><i class="fa fa-plus"></i></span>', ['/clients/create'], ['role'=>'modal-remote',])?>
                        <?= Html::a('<span class="btn btn-default btn-sm">Заработано</span>', ['/site/earned'], ['data-pjax'=>0,])?>
                        <a class="btn btn-default btn-sm" href="#">Сайт</a>
                    </div>
                </div>
            </div>
        </div>

        <div id="ajaxCrudDatatable">
            <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            //'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'panelBeforeTemplate' => '&nbsp;',
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
            'headingOptions' => ['style' => 'display: none;'],
            'after'=>'',
            ]
            ])?>
        </div>

    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "size" => "modal-lg",
    "options" => [
        "tabindex" => -1,
    ],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/clients/search.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;


$this->title = 'Список комнаты';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>

    <div id="ajaxCrudDatatable">
        <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $houses_dataProvider,
            'pjax'=>true,
            'columns' => require(__DIR__.'/house_columns.php'),
            'toolbar'=> [
                ['content'=> '',],
            ],          
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'summary' => false,
            'panel' => [
                'type' => 'primary', 
                'headingOptions' => "",
                'footerOptions' => "",
                /*'after'=>BulkButtonWidget::widget([
                            'buttons'=>Html::a('<i class="glyphicon glyphicon-check"></i>&nbsp; Выбрать',
                                ["bulk-select", 'client_id' => $model->id] ,
                                [
                                    "class"=>"btn btn-info btn-xs",
                                    'role'=>'modal-remote-bulk',
                                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                    'data-request-method'=>'post',
                                    'data-confirm-title'=>'Подтвердите действие',
                                    'data-confirm-message'=>'Вы уверены что хотите добавить эти элементы?'
                                ]),
                        ]).                        
                        '<div class="clearfix"></div>',*/
            ]
        ])?>
    </div>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",
    "options" => [
        "tabindex" => false,
    ],
])?>
<?php Modal::end(); ?>

views/clients/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Clients */
?>
<div class="clients-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>