models/User.php
<?php

namespace app\models;

class User extends Users/*\yii\base\Object*/ implements \yii\web\IdentityInterface
{
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['login' => $username]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
       return $this->password === md5($password);
    }
}

controllers/ClientsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Clients;
use app\models\ClientsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\House;
use app\models\ClientsHouses;

/**
 * ClientsController implements the CRUD actions for Clients model.
 */
class ClientsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                   [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulkdelete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Clients models.
     * @return mixed
     */
    public function actionIndex($type = 0)
    {    
        $searchModel = new ClientsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$type);

        $apartment_long = House::find()->where(['house_type' => 1])->count();
        $room_long = House::find()->where(['house_type' => 3])->count();
        $home_long = House::find()->where(['house_type' => 5])->count();

        $apartment_short = House::find()->where(['house_type' => 2])->count();
        $room_short= House::find()->where(['house_type' => 4])->count();
        $home_short = House::find()->where(['house_type' => 6])->count();

        $clients = Clients::find()->count();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'apartment_long' => $apartment_long,
            'room_long' => $room_long,
            'home_long' => $home_long,
            'apartment_short' => $apartment_short,
            'room_short' => $room_short,
            'home_short' => $home_short,
            'clients' => $clients,
        ]);
    }

    /**
     * Displays a single Clients model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $apartment_long = House::find()->where(['house_type' => 1])->count();
        $room_long = House::find()->where(['house_type' => 3])->count();
        $home_long = House::find()->where(['house_type' => 5])->count();

        $apartment_short = House::find()->where(['house_type' => 2])->count();
        $room_short= House::find()->where(['house_type' => 4])->count();
        $home_short = House::find()->where(['house_type' => 6])->count();

        $clients = Clients::find()->count();

        return $this->render('view', [
            'model' => $this->findModel($id),
            'id' => $id,
            'apartment_long' => $apartment_long,
            'room_long' => $room_long,
            'home_long' => $home_long,
            'apartment_short' => $apartment_short,
            'room_short' => $room_short,
            'home_short' => $home_short,
            'clients' => $clients,
        ]);
        
    }

    /**
     * Creates a new Clients model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Clients();  

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Клиенты",
                    'content'=>'<span class="text-success">Успешно выпольнено</span>',
                    'footer'=> Html::button('Ок',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Создать ещё',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])
        
                ];         
            }else{           
                return [
                    'title'=> "Добавить",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }       
    }

    public function actionAdd()
    {
        $request = Yii::$app->request;
        $model = new Clients();  

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить",
                    'size' => 'large',
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceClose'=>true,
                ];         
            }else{           
                return [
                    'title'=> "Добавить",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }       
    }
    public function actionAddnew($id)
    {
        $request = Yii::$app->request;
        $model = new Clients();  
        $house = House::findOne($id);

        Yii::$app->response->format = Response::FORMAT_JSON;
        if($model->load($request->post()) && $model->save()){
            $house->client_id = $model->id;
            $house->save();
            $house->setClientsHouse();
            return [
                'forceClose'=>true,
                'forceReload'=>'#datas-pjax',
            ];         
        }else{  
            if($house->house_type == 1)
            {
                $model->type = 1; 
                $model->category = 1; 
            }
            if($house->house_type == 2)
            {
                $model->type = 1; 
                $model->category = 2; 
            }
            if($house->house_type == 3)
            {
                $model->type = 2; 
                $model->category = 1; 
            }
            if($house->house_type == 4)
            {
                $model->type = 2;
                $model->category = 2; 
            }
            if($house->house_type == 5)
            {
                $model->type = 3; 
                $model->category = 1; 
            }
            if($house->house_type == 6)
            {
                $model->type = 3; 
                $model->category = 2; 
            } 
            return [
                'title'=> "Добавить",
                'size' => 'large',
                'content'=>$this->renderAjax('_from_new', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])        
            ];         
        }    
    }
    public function actionSearch($client_id)
    {
        $request = Yii::$app->request;
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = $this->findModel($client_id);
        $houses_dataProvider = $model->getHouses();

        if($request->isGet)
        {
            return [
                'title'=> "Искать",
                'size' => 'large',
                'content'=>$this->renderAjax('search', [
                    'houses_dataProvider' => $houses_dataProvider,
                    'model' => $model,
                ]),      
            ];         
        }
        else
        {           
            return [
                'forceClose'=>true,
            ];         
        }              
    }

    /**
     * Updates an existing Clients model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);  
        Yii::$app->response->format = Response::FORMAT_JSON;

        if($model->last_call != null ) $model->last_call = \Yii::$app->formatter->asDate($model->last_call, 'php:d.m.Y');

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Users;
use app\models\House;
use app\models\Clients;
use app\models\ClientsHouses;
use app\models\Nastroyka;

class SiteController extends Controller
{
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['dashboard', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->isGuest) { 
            return $this->redirect('site/boards-project');
        }else
        {
            return $this->redirect(['site/login']);
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Рабочий стол
     * через этот екшн заходим на Рабочий стол
     * @return Response|string
     */     
    public function actionDashboard()
    {
      if (Yii::$app->user->isGuest) { 
        return $this->redirect(['site/login']);
      }
        return $this->render('dashboard', [
            'all_tasks' => $result1,
            'result' => $result,
            'comment' => $comment,
            'total_hour' => $total_hour,
            'tasks' => $all_tasks,
        ]);
    }
    public function actionHouse()
    {
        return $this->redirect(['house/apartment', 'type' => 4]);
    }
    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
         Yii::$app->user->logout();

        $this->redirect(['login']);
    }

    public function actionAvtorizatsiya()
    {
      if(isset(Yii::$app->user->identity->id))
      {
        return $this->render('error');
      }        
      else
      {
          Yii::$app->user->logout();
          $this->redirect(['login']);
      }
    }
    
    public function actionEarned($year = null, $month = null)
    { 
      if($year == null)  $year = date('Y');  
      if($month == null)  $month = date('m');
      $apartment_long = House::find()->where(['house_type' => 1])->count();
      $room_long = House::find()->where(['house_type' => 3])->count();
      $home_long = House::find()->where(['house_type' => 5])->count();

      $apartment_short = House::find()->where(['house_type' => 2])->count();
      $room_short= House::find()->where(['house_type' => 4])->count();
      $home_short = House::find()->where(['house_type' => 6])->count();

      $clients = Clients::find()->count();

      $min_litsenzed = ClientsHouses::find()->min('date_add_commission');
      $max_litsenzed = ClientsHouses::find()->max('date_add_commission');

      return $this->render('earned', [
          'model' => new ClientsHouses(),
          'apartment_long' => $apartment_long,
          'room_long' => $room_long,
          'home_long' => $home_long,
          'apartment_short' => $apartment_short,
          'room_short' => $room_short,
          'home_short' => $home_short,
          'clients' => $clients,
          'year' => $year,
          'month' => $month,
          'min_litsenzed' => \Yii::$app->formatter->asDate($min_litsenzed. Yii::$app->getTimeZone(), 'php:Y'),
          'max_litsenzed' => \Yii::$app->formatter->asDate($max_litsenzed. Yii::$app->getTimeZone(), 'php:Y'),
      ]);
    }

    // через этот екшн можно войти на инструкцию
    public function actionInstruksion()
    {
        if (Yii::$app->user->isGuest)   return $this->redirect(['site/login']);
        return $this->render('instruksion', []);        
    }

    public function actionMap()
    {
      return $this->render('map', []);
    }

    public function actionTuning()
    {
        $request = Yii::$app->request;
        $model = Nastroyka::find()->where(['user_id' => Yii::$app->user->id])->one();
        if($model == null){
            $model = new Nastroyka();
            $model->user_id = Yii::$app->user->id;
            $model->coordinate_x = '55.753187580818675';
            $model->coordinate_y = '37.62333811759736';
            $model->city = "Москва";
            $model->location_metro = "метро Площадь Революции";
            $model->address = "улица Ильинка";
            $model->dom = " 7";
        }
/*echo "<pre>";
print_r($request->post());
echo "</pre>";
die;*/
        if ($model->load($request->post()) && $model->save()) {
            return $this->redirect(['site/dashboard']);
        } else {
            return $this->render('_form_nastroyka', [
                'model' => $model,
            ]);
        }
    }
}

views/users/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-form">

    <?php $form = ActiveForm::begin(); ?>

        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'fio')->textInput(['maxlength' => true]) ?>        
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'type')->dropDownList($model->getType(), ['prompt' => 'Выберите тип', 'id' => 'type']) ?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'birthday')->widget(
                        DatePicker::className(), [
                            'inline' => false,
                            'language' => 'ru',
                            'clientOptions' => [
                                'autoclose' => true,
                                'format' => 'dd.mm.yyyy',
                                'startView'=>'decade',
                            ]
                        ])
                    ?>
            </div>
        </div>

        <div class="row">

            <div class="col-md-4">
                <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
            </div>

            <div class="col-md-4">
                <?= $form->field($model, 'login')->textInput(['maxlength' => true]) ?>        
            </div>

            <div class="col-md-4">
                <?= $form->field($model, 'password')->textInput(['maxlength' => true]) ?>        
            </div>
        </div>



        <div class="row" >

            <div class="col-md-6">
                <?= $form->field($model, 'telephone')->textInput(['maxlength' => true]) ?>
            </div>

            <div class="col-md-6" id="licensed_user" <?php if($model->type != 2) echo 'style=" display: none;"';?>>
                <?= $form->field($model, 'license')->dropDownList($model->getLisenceType(), ['prompt' => 'Выберите лицензию']) ?>
            </div>
            
            <div class="col-md-6" id="agent" <?php if($model->type != 3) echo 'style=" display: none;"';?> >
                <?= $form->field($model, 'licensed_user')->dropDownList($model->getLisencedUser(), ['prompt' => 'Выберите ']) ?>
            </div>
        </div>

        <div style="display: none">

            <div class="col-md-3">
                <?= $form->field($model, 'balance')->widget(\yii\widgets\MaskedInput::className(), [
                 'clientOptions' => [
                    'alias' =>  'decimal',
                    'groupSeparator' => ' ',
                    'autoGroup' => true
                ],
                ]) ?>
            </div>
            <?= $form->field($model, 'creation_date')->textInput(['value' => date('Y-m-d H:i:s')]) ?>
            <?= $form->field($model, 'end_date')->textInput() ?>
        </div>

    	<?php if (!Yii::$app->request->isAjax){ ?>
    	  	<div class="form-group">
    	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    	    </div>
    	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>
<?php 
$this->registerJs(<<<JS
    $('#type').on('change', function() 
    {  
        var type = this.value; //console.log(type);
        $('#licensed_user').hide(); $('#agent').hide();
        if(type == 2) $('#licensed_user').show(); 
        if(type == 3) $('#agent').show(); 
    }
);
JS
);
?>

views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UsersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'fio') ?>

    <?= $form->field($model, 'login') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'telephone') ?>

    <?php // echo $form->field($model, 'city') ?>

    <?php // echo $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'dostup') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/users/add-agent-form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;

?>

<div class="users-form">

    <?php $form = ActiveForm::begin(); ?>

        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'fio')->textInput(['maxlength' => true]) ?>        
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'telephone')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'birthday')->widget(
                        DatePicker::className(), [
                            'inline' => false,
                            'language' => 'ru',
                            'clientOptions' => [
                                'autoclose' => true,
                                'format' => 'dd.mm.yyyy',
                                'startView'=>'decade',
                            ]
                        ])
                    ?>
            </div>
        </div>

        <div class="row">

            <div class="col-md-4">
                <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
            </div>

            <div class="col-md-4">
                <?= $form->field($model, 'login')->textInput(['maxlength' => true]) ?>        
            </div>

            <div class="col-md-4">
                <?= $form->field($model, 'password')->textInput(['maxlength' => true]) ?>        
            </div>
        </div>

        <div style="display: none">
            <?= $form->field($model, 'license')->dropDownList($model->getLisenceType(), ['prompt' => 'Выберите лицензию']) ?>                        
            <?= $form->field($model, 'licensed_user')->dropDownList($model->getLisencedUser(), ['prompt' => 'Выберите ']) ?>
            <?= $form->field($model, 'type')->dropDownList($model->getType(), ['prompt' => 'Выберите тип', 'id' => 'type']) ?>            
            <?= $form->field($model, 'balance')->widget(\yii\widgets\MaskedInput::className(), [
             'clientOptions' => [
                'alias' =>  'decimal',
                'groupSeparator' => ' ',
                'autoGroup' => true
            ],
            ]) ?>            
            <?= $form->field($model, 'creation_date')->textInput(['value' => date('Y-m-d')]) ?>
            <?= $form->field($model, 'end_date')->textInput() ?>
        </div>

    <?php ActiveForm::end(); ?>
    
</div>

views/users/add-agent.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

?>
<div class="users-create">
    <?= $this->render('add-agent-form', [
        'model' => $model,
    ]) ?>
</div>

views/users/agents_columns.php
<?php
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'fio',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'email',
    ],    
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'birthday',
        'content' => function ($data) {
            return \Yii::$app->formatter->asDate($data->birthday, 'php:d.m.Y');
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'telephone',
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'template' => '{update}{delete}',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>[/*'role'=>'modal-remote',*/ 'data-pjax' => 0,'title'=>'','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Подтвердите действие',
                          'data-confirm-message'=>'Вы уверены что хотите удалить данного элемента?'], 
    ],

];   

views/users/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

?>
<div class="users-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/users/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = "Пользователи";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="panel panel-inverse users-index">
    <div class="panel-heading">
<!--        <div class="panel-heading-btn">-->
<!--        </div>-->
        <h4 class="panel-title">Пользователи</h4>
    </div>
    <div class="panel-body">

        <div class="col-xs-12">
            <div class="row">
                <div class="col-sm-6 col-lg-4">
                    <h5>На длительный срок <span><?=($apartment_long + $room_long + $home_long)?></span></h5>
                    <div class="form-group">
                        <?= Html::a('<span class="btn btn-default btn-sm">Квартиры <span>'.$apartment_long.'</span></span>', ['/house/apartment','type' => 1], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 1], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm">Комнаты <span>'.$room_long.'</span></span>', ['/house/apartment','type' => 2], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 3], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm">Дома <span>'.$home_long.'</span></span>', ['/house/apartment','type' => 3], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 5], ['data-pjax'=>0,])?> 
                    </div>
                </div>
                <div class="col-sm-6 col-lg-4">
                    <h5>Посуточно <span><?=($apartment_short + $room_short + $home_short)?></span></h5>
                    <div class="form-group">
                        <?= Html::a('<span class="btn btn-default btn-sm">Квартиры <span>'.$apartment_short.'</span></span>', ['/house/apartment','type' => 1], ['data-pjax'=>0,])?>
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 2], ['data-pjax'=>0,])?>
                        <?= Html::a('<span class="btn btn-default btn-sm">Комнаты <span>'.$room_short.'</span></span>', ['/house/apartment','type' => 2], ['data-pjax'=>0,])?>
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 4], ['data-pjax'=>0,])?>
                        <?= Html::a('<span class="btn btn-default btn-sm">Дома <span>'.$home_short.'</span></span>', ['/house/apartment','type' => 3], ['data-pjax'=>0,])?> 
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/house/apartment-create', 'type' => 6], ['data-pjax'=>0,])?>
                    </div>
                </div>
                <div class="col-sm-4 col-md-3">
                    <h5>Доп. нав</h5>
                    <div class="form-group">
                        <?= Html::a('<span class="btn btn-default btn-sm">Клиенты <span>'.$clients.'</span></span>', ['/clients'], ['data-pjax'=>0,])?>
                        <?= Html::a('<span class="btn btn-default btn-sm"><i class="fa fa-plus"></i></span>', ['/clients/add'], ['role'=>'modal-remote',])?>
                        <?= Html::a('<span class="btn btn-default btn-sm">Заработано</span>', ['/site/earned'], ['data-pjax'=>0,])?>
                        <a class="btn btn-default btn-sm" href="#">Сайт</a>
                    </div>
                </div>
            </div>
            <br>
        </div>

        <div id="ajaxCrudDatatable">
            <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            //'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'panelBeforeTemplate' =>    Html::a('Добавить <i class="fa fa-plus"></i>', ['create'],
                    ['role'=>'modal-remote','title'=> 'Добавить Пользователя','class'=>'btn btn-success']),
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
            'headingOptions' => ['style' => 'display: none;'],
            'after'=>'',
            ]
            ])?>
        </div>
    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "size" => "modal-lg",
    "options" => [
        "tabindex" => -1,
    ],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/users/transfer.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

?>
<div class="users-create">
    <?= $this->render('transfer_form', [
        'model' => $model,
    ]) ?>
</div>

views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
?>
<div class="users-update">

    <?= $this->render('update_form', [
        'model' => $model,
    ]) ?>

</div>